### PR TITLE
i10:use WML client lib

### PR DESCRIPTION
**Pull request by ptitzler**
Delivers #10:

- Use Watson Machine Learning Python client library
- Add Python 3.5 support

### CODE REVIEW

**Review by scottdangelo — COMMENTED** [review]
Did you accidentally push up 2 copies of `wml-product-recommendation-engine.ipynb` ?
One in the top dir, and one in `notebooks/`?

**Comment by ptitzler** [comment]
oops, yes. sorry.

**Comment by scottdangelo** [comment]
Are you running the `Python with Spark 3.5` kernel for this?
I'm getting an error when I run the cell
 `from watson_machine_learning_client import WatsonMachineLearningAPIClient`:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-19581e9412f7> in <module>()
----> 1 from watson_machine_learning_client import WatsonMachineLearningAPIClient

ImportError: No module named 'watson_machine_learning_client'
```

**Comment by ptitzler** [comment]
The cell after that installs the library, if required. (See comment there)
I don't think it is installed by default in any of the kernels. I tested with Python 3.5/Spark 2.x.

**Pull request merged**
